name: learn-github-actions
on: [push]
jobs:
  check-bats-version: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Hello World!"
      
  example-secrets: 
    runs-on: ubuntu-latest
    steps:
      - name: Retrive secret
        env:
          super_secret: ${{secrets.THIS_IS_MY_SUPER_DUPER_SECRET_PASSWORD}}
        run: |
          echo "$super_secret"
