on: [push]

jobs: 
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps: 
      - uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-from-javascript-action
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}" 
